name: Auto assign to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign_to_project:
    uses: koinos/koinos-github-workflows/.github/workflows/add_to_project.yml@master
    secrets:
      github-token: ${{ secrets.ISSUE_MANAGEMENT_TOKEN }}
