name: Assign pull request to project

on:
  pull_request:
    types: [opened]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign pull request to project
    steps:

    - name: Assign pull request to project
      uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
