name: Auto assign to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue/pull request to project
    steps:

    - name: Assign issues with `bug` or `enhancement` label to project
      uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/koinos/projects/6
        github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
        labeled: bug, enhancement
        label-operator: OR
